name: Validate Integration

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - name: HASS validation
        uses: home-assistant/actions/hassfest@master
