name: Release

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: ncipollo/release-action@v1
      with:
        makeLatest: true
        body: "Home Assistnat Uconnect Release"
